default: &default
  adapter: postgresql
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: hans_development

test:
  <<: *default
  database: hans_test

production:
  <<: *default
  database: hans_production
